// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vneialppjjccehfimpkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZWlhbHBwampjY2VoZmltcGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDkzNDMsImV4cCI6MjA2Nzg4NTM0M30.lubEWUR7OG0a2aBDrgtvwi0pyn5ig071FYZPzmx8qdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});